### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by DharaneedaranKS** [IEEE-NITK/Digital-Stethoscope#2]
Need to find a better dataset, that doesn't have lopsided class issue. The restrictions are 
- Should be a Auditory Respiration dataset
- Check for the division across classes 
- should be large enough ( minimum 1000 datasets )

**Comment by CHANDAN-2003** [comment]
Link 1 - https://gitlab.com/techsupportHF/HF_Lung_V1
Link 2 - https://www.sciencedirect.com/science/article/pii/S2352340921001979

**Comment by gagan20003** [comment]
https://data.mendeley.com/datasets/jwyy9np4gv/3

**Comment by DharaneedaranKS** [comment]
> Link 1 - https://gitlab.com/techsupportHF/HF_Lung_V1 Link 2 - https://www.sciencedirect.com/science/article/pii/S2352340921001979

I am not sure about these that much but still good finds

**Comment by DharaneedaranKS** [comment]
> https://data.mendeley.com/datasets/jwyy9np4gv/3

okay will definitely try once with these

**Comment by DharaneedaranKS** [comment]
> > https://data.mendeley.com/datasets/jwyy9np4gv/3
> 
> okay will definitely try once with these

Okay very very messed up annotations, we can use it, but it technically has only 112 datasets in an essence. Either we can approach it by sorting the annotations or go ahead and change the data set.
